// Generated by `bun run db:generate` from drizzle/. Do not edit.
import type { MigrationMeta } from "drizzle-orm/migrator";

export const migrations: MigrationMeta[] = [
  {
    "sql": [
      "CREATE TYPE \"connector_reach\" AS ENUM('dial');",
      "\nCREATE TYPE \"compute_kind\" AS ENUM('serverless', 'container');",
      "\nCREATE TYPE \"deployment_kind\" AS ENUM('deploy', 'preview-up', 'preview-rm', 'rollback', 'destroy');",
      "\nCREATE TYPE \"deployment_outcome\" AS ENUM('succeeded', 'failed');",
      "\nCREATE TYPE \"environment_class\" AS ENUM('production', 'preview');",
      "\nCREATE TYPE \"framework\" AS ENUM('nextjs', 'react', 'astro', 'remix', 'nuxt', 'sveltekit', 'node', 'express', 'fastify', 'hono', 'bun', 'deno', 'go', 'python', 'django', 'rust');",
      "\nCREATE TABLE \"account\" (\n\t\"id\" text PRIMARY KEY,\n\t\"account_id\" text NOT NULL,\n\t\"provider_id\" text NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"access_token\" text,\n\t\"refresh_token\" text,\n\t\"id_token\" text,\n\t\"access_token_expires_at\" timestamp,\n\t\"refresh_token_expires_at\" timestamp,\n\t\"scope\" text,\n\t\"password\" text,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp NOT NULL\n);\n",
      "\nCREATE TABLE \"device_code\" (\n\t\"id\" text PRIMARY KEY,\n\t\"device_code\" text NOT NULL,\n\t\"user_code\" text NOT NULL,\n\t\"user_id\" text,\n\t\"expires_at\" timestamp NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"last_polled_at\" timestamp,\n\t\"polling_interval\" integer,\n\t\"client_id\" text,\n\t\"scope\" text\n);\n",
      "\nCREATE TABLE \"invitation\" (\n\t\"id\" text PRIMARY KEY,\n\t\"organization_id\" text NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"role\" text,\n\t\"status\" text DEFAULT 'pending' NOT NULL,\n\t\"expires_at\" timestamp NOT NULL,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"inviter_id\" text NOT NULL\n);\n",
      "\nCREATE TABLE \"jwks\" (\n\t\"id\" text PRIMARY KEY,\n\t\"public_key\" text NOT NULL,\n\t\"private_key\" text NOT NULL,\n\t\"created_at\" timestamp NOT NULL,\n\t\"expires_at\" timestamp,\n\t\"alg\" text,\n\t\"crv\" text\n);\n",
      "\nCREATE TABLE \"member\" (\n\t\"id\" text PRIMARY KEY,\n\t\"organization_id\" text NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"role\" text DEFAULT 'member' NOT NULL,\n\t\"created_at\" timestamp NOT NULL\n);\n",
      "\nCREATE TABLE \"organization\" (\n\t\"id\" text PRIMARY KEY,\n\t\"name\" text NOT NULL,\n\t\"slug\" text NOT NULL UNIQUE,\n\t\"logo\" text,\n\t\"created_at\" timestamp NOT NULL,\n\t\"metadata\" text\n);\n",
      "\nCREATE TABLE \"session\" (\n\t\"id\" text PRIMARY KEY,\n\t\"expires_at\" timestamp NOT NULL,\n\t\"token\" text NOT NULL UNIQUE,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp NOT NULL,\n\t\"ip_address\" text,\n\t\"user_agent\" text,\n\t\"user_id\" text NOT NULL,\n\t\"active_organization_id\" text\n);\n",
      "\nCREATE TABLE \"user\" (\n\t\"id\" text PRIMARY KEY,\n\t\"name\" text NOT NULL,\n\t\"email\" text NOT NULL UNIQUE,\n\t\"email_verified\" boolean DEFAULT false NOT NULL,\n\t\"image\" text,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"verification\" (\n\t\"id\" text PRIMARY KEY,\n\t\"identifier\" text NOT NULL,\n\t\"value\" text NOT NULL,\n\t\"expires_at\" timestamp NOT NULL,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"connector\" (\n\t\"id\" text PRIMARY KEY,\n\t\"organization_id\" text NOT NULL,\n\t\"target\" text NOT NULL,\n\t\"vendor\" text NOT NULL,\n\t\"compute\" \"compute_kind\",\n\t\"reach\" \"connector_reach\" DEFAULT 'dial'::\"connector_reach\" NOT NULL,\n\t\"url\" text,\n\t\"public_key\" text,\n\t\"tls_pin\" text,\n\t\"version\" text,\n\t\"capabilities\" jsonb DEFAULT '[]' NOT NULL,\n\t\"connected_at\" timestamp,\n\t\"last_seen_at\" timestamp,\n\t\"last_denied\" jsonb,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"deployment\" (\n\t\"id\" text PRIMARY KEY,\n\t\"project_id\" text NOT NULL,\n\t\"run_id\" text NOT NULL,\n\t\"kind\" \"deployment_kind\" NOT NULL,\n\t\"environment_class\" \"environment_class\" NOT NULL,\n\t\"environment_identity\" text DEFAULT '' NOT NULL,\n\t\"promotion_id\" text,\n\t\"tag\" text,\n\t\"provider_name\" text NOT NULL,\n\t\"provider_region\" text,\n\t\"target\" text NOT NULL,\n\t\"edge_kind\" text,\n\t\"outcome\" \"deployment_outcome\" NOT NULL,\n\t\"error\" text,\n\t\"trigger\" jsonb NOT NULL,\n\t\"git\" jsonb,\n\t\"cli_version\" text,\n\t\"started_at\" timestamp,\n\t\"deployed_at\" timestamp NOT NULL,\n\t\"trace\" jsonb NOT NULL,\n\t\"topology\" jsonb NOT NULL,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"project\" (\n\t\"id\" text PRIMARY KEY,\n\t\"organization_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"slug\" text NOT NULL,\n\t\"description\" text,\n\t\"frameworks\" \"framework\"[] DEFAULT '{}'::\"framework\"[] NOT NULL,\n\t\"created_by\" text,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp DEFAULT now() NOT NULL\n);\n",
      "\nCREATE INDEX \"account_userId_idx\" ON \"account\" (\"user_id\");",
      "\nCREATE INDEX \"invitation_organizationId_idx\" ON \"invitation\" (\"organization_id\");",
      "\nCREATE INDEX \"invitation_email_idx\" ON \"invitation\" (\"email\");",
      "\nCREATE INDEX \"member_organizationId_idx\" ON \"member\" (\"organization_id\");",
      "\nCREATE INDEX \"member_userId_idx\" ON \"member\" (\"user_id\");",
      "\nCREATE UNIQUE INDEX \"organization_slug_uidx\" ON \"organization\" (\"slug\");",
      "\nCREATE INDEX \"session_userId_idx\" ON \"session\" (\"user_id\");",
      "\nCREATE INDEX \"verification_identifier_idx\" ON \"verification\" (\"identifier\");",
      "\nCREATE UNIQUE INDEX \"connector_organization_target_uidx\" ON \"connector\" (\"organization_id\",\"target\");",
      "\nCREATE UNIQUE INDEX \"deployment_run_uidx\" ON \"deployment\" (\"project_id\",\"run_id\");",
      "\nCREATE INDEX \"deployment_project_latest_idx\" ON \"deployment\" (\"project_id\",\"environment_class\",\"deployed_at\");",
      "\nCREATE UNIQUE INDEX \"project_organizationId_slug_uidx\" ON \"project\" (\"organization_id\",\"slug\");",
      "\nALTER TABLE \"account\" ADD CONSTRAINT \"account_user_id_user_id_fkey\" FOREIGN KEY (\"user_id\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"invitation\" ADD CONSTRAINT \"invitation_organization_id_organization_id_fkey\" FOREIGN KEY (\"organization_id\") REFERENCES \"organization\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"invitation\" ADD CONSTRAINT \"invitation_inviter_id_user_id_fkey\" FOREIGN KEY (\"inviter_id\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"member\" ADD CONSTRAINT \"member_organization_id_organization_id_fkey\" FOREIGN KEY (\"organization_id\") REFERENCES \"organization\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"member\" ADD CONSTRAINT \"member_user_id_user_id_fkey\" FOREIGN KEY (\"user_id\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"session\" ADD CONSTRAINT \"session_user_id_user_id_fkey\" FOREIGN KEY (\"user_id\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"connector\" ADD CONSTRAINT \"connector_organization_id_organization_id_fkey\" FOREIGN KEY (\"organization_id\") REFERENCES \"organization\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"deployment\" ADD CONSTRAINT \"deployment_project_id_project_id_fkey\" FOREIGN KEY (\"project_id\") REFERENCES \"project\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"project\" ADD CONSTRAINT \"project_organization_id_organization_id_fkey\" FOREIGN KEY (\"organization_id\") REFERENCES \"organization\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"project\" ADD CONSTRAINT \"project_created_by_user_id_fkey\" FOREIGN KEY (\"created_by\") REFERENCES \"user\"(\"id\") ON DELETE SET NULL;"
    ],
    "bps": true,
    "folderMillis": 1791284001000,
    "hash": "d2b89eeb5d022ac8a5580aed8ca06594823095ddfd4512349de3ff57f49aeb29",
    "name": "20261006105321_initial"
  },
  {
    "sql": [
      "CREATE TYPE \"environment_event_kind\" AS ENUM('preview-removed', 'destroyed');",
      "\nCREATE TABLE \"environment_event\" (\n\t\"id\" text PRIMARY KEY,\n\t\"project_id\" text NOT NULL,\n\t\"run_id\" text NOT NULL,\n\t\"kind\" \"environment_event_kind\" NOT NULL,\n\t\"environment_class\" \"environment_class\" NOT NULL,\n\t\"environment_identity\" text DEFAULT '' NOT NULL,\n\t\"occurred_at\" timestamp NOT NULL,\n\t\"git\" jsonb,\n\t\"ci\" jsonb,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX \"environment_event_run_uidx\" ON \"environment_event\" (\"project_id\",\"run_id\");",
      "\nCREATE INDEX \"environment_event_project_idx\" ON \"environment_event\" (\"project_id\",\"occurred_at\");",
      "\nALTER TABLE \"environment_event\" ADD CONSTRAINT \"environment_event_project_id_project_id_fkey\" FOREIGN KEY (\"project_id\") REFERENCES \"project\"(\"id\") ON DELETE CASCADE;"
    ],
    "bps": true,
    "folderMillis": 1791409166000,
    "hash": "fb1dc78f70e606ae079ae5a91141aa408d51fbfe074f06d891fa19cad406f6fc",
    "name": "20261007213926_environment_event"
  },
  {
    "sql": [
      "ALTER TABLE \"deployment\" ALTER COLUMN \"kind\" SET DATA TYPE text;",
      "\nDROP TYPE \"deployment_kind\";",
      "\nCREATE TYPE \"deployment_kind\" AS ENUM('deploy', 'preview-up', 'rollback');",
      "\nALTER TABLE \"deployment\" ALTER COLUMN \"kind\" SET DATA TYPE \"deployment_kind\" USING \"kind\"::\"deployment_kind\";"
    ],
    "bps": true,
    "folderMillis": 1791409436000,
    "hash": "7252cd0832c101f5e04827157e405c94a924abde9c715473184bf89ff25e2096",
    "name": "20261007214356_deployment_kind_promotes_only"
  },
  {
    "sql": [
      "ALTER TYPE \"framework\" RENAME VALUE 'nextjs' TO 'next';\n"
    ],
    "bps": true,
    "folderMillis": 1791409554000,
    "hash": "bb1b5583400c76e02d268353cebe3cef1e0d3607c43a9943d77be3d7036fefdb",
    "name": "20261007214554_framework_nextjs_renamed_next"
  },
  {
    "sql": [
      "ALTER TABLE \"project\" ALTER COLUMN \"frameworks\" SET DATA TYPE text[];",
      "\nALTER TABLE \"project\" ALTER COLUMN \"frameworks\" DROP DEFAULT;",
      "\nDROP TYPE \"framework\";",
      "\nCREATE TYPE \"framework\" AS ENUM('next', 'react', 'astro', 'remix', 'nuxt', 'sveltekit', 'node', 'express', 'fastify', 'hono', 'bun', 'deno', 'go', 'python', 'django', 'rust');",
      "\nALTER TABLE \"project\" ALTER COLUMN \"frameworks\" SET DATA TYPE \"framework\"[] USING \"frameworks\"::\"framework\"[];",
      "\nALTER TABLE \"project\" ALTER COLUMN \"frameworks\" SET DEFAULT '{}'::\"framework\"[];"
    ],
    "bps": true,
    "folderMillis": 1791409561000,
    "hash": "e2b115b901b7eca9f3b38e2ff1f6ff319415fb6c1685f086d8d6ddf251f9d8e4",
    "name": "20261007214601_framework_next"
  },
  {
    "sql": [
      "ALTER TYPE \"environment_class\" RENAME TO \"tier\";",
      "\nALTER TABLE \"deployment\" RENAME COLUMN \"run_id\" TO \"deployment_id\";",
      "\nALTER TABLE \"deployment\" RENAME COLUMN \"environment_class\" TO \"tier\";",
      "\nALTER TABLE \"environment_event\" RENAME COLUMN \"run_id\" TO \"deployment_id\";",
      "\nALTER TABLE \"environment_event\" RENAME COLUMN \"environment_class\" TO \"tier\";",
      "\nALTER INDEX \"deployment_run_uidx\" RENAME TO \"deployment_deployment_id_uidx\";",
      "\nALTER INDEX \"environment_event_run_uidx\" RENAME TO \"environment_event_deployment_id_uidx\";",
      "\nUPDATE \"deployment\" SET \"topology\" = jsonb_set(\"topology\", '{apps}', (\n\tSELECT jsonb_agg(\n\t\tCASE WHEN \"app\" ? 'deploymentId'\n\t\t\tTHEN (\"app\" - 'deploymentId') || jsonb_build_object('release', \"app\" -> 'deploymentId')\n\t\t\tELSE \"app\"\n\t\tEND ORDER BY \"position\")\n\tFROM jsonb_array_elements(\"topology\" -> 'apps') WITH ORDINALITY AS \"apps\" (\"app\", \"position\")\n)) WHERE jsonb_path_exists(\"topology\", '$.apps[*].deploymentId');"
    ],
    "bps": true,
    "folderMillis": 1791418098000,
    "hash": "cfd11dfd9db3237537c3612ced62c0e865fdda1dacd3fe2ba8a3ea4db72f060e",
    "name": "20261008000818_tier_deployment_id_release"
  },
  {
    "sql": [
      "CREATE TYPE \"git_kind\" AS ENUM('github');",
      "\nCREATE TABLE \"git_app\" (\n\t\"id\" text PRIMARY KEY,\n\t\"organization_id\" text,\n\t\"kind\" \"git_kind\" NOT NULL,\n\t\"app_id\" text NOT NULL,\n\t\"slug\" text NOT NULL,\n\t\"private_key_enc\" text NOT NULL,\n\t\"webhook_secret_enc\" text NOT NULL,\n\t\"client_id\" text NOT NULL,\n\t\"client_secret_enc\" text NOT NULL,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"git_delivery\" (\n\t\"git_app_id\" text,\n\t\"delivery_id\" text,\n\t\"received_at\" timestamp DEFAULT now() NOT NULL,\n\tCONSTRAINT \"git_delivery_pkey\" PRIMARY KEY(\"git_app_id\",\"delivery_id\")\n);\n",
      "\nCREATE TABLE \"git_installation\" (\n\t\"id\" text PRIMARY KEY,\n\t\"git_app_id\" text NOT NULL,\n\t\"organization_id\" text NOT NULL,\n\t\"external_id\" text NOT NULL,\n\t\"account\" text NOT NULL,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"project_repo\" (\n\t\"project_id\" text PRIMARY KEY,\n\t\"installation_id\" text NOT NULL,\n\t\"repo_id\" text NOT NULL,\n\t\"full_name\" text NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX \"git_app_kind_appId_uidx\" ON \"git_app\" (\"kind\",\"app_id\");",
      "\nCREATE INDEX \"git_delivery_receivedAt_idx\" ON \"git_delivery\" (\"received_at\");",
      "\nCREATE UNIQUE INDEX \"git_installation_gitAppId_externalId_uidx\" ON \"git_installation\" (\"git_app_id\",\"external_id\");",
      "\nCREATE INDEX \"project_repo_installationId_repoId_idx\" ON \"project_repo\" (\"installation_id\",\"repo_id\");",
      "\nALTER TABLE \"git_app\" ADD CONSTRAINT \"git_app_organization_id_organization_id_fkey\" FOREIGN KEY (\"organization_id\") REFERENCES \"organization\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"git_delivery\" ADD CONSTRAINT \"git_delivery_git_app_id_git_app_id_fkey\" FOREIGN KEY (\"git_app_id\") REFERENCES \"git_app\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"git_installation\" ADD CONSTRAINT \"git_installation_git_app_id_git_app_id_fkey\" FOREIGN KEY (\"git_app_id\") REFERENCES \"git_app\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"git_installation\" ADD CONSTRAINT \"git_installation_organization_id_organization_id_fkey\" FOREIGN KEY (\"organization_id\") REFERENCES \"organization\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"project_repo\" ADD CONSTRAINT \"project_repo_project_id_project_id_fkey\" FOREIGN KEY (\"project_id\") REFERENCES \"project\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"project_repo\" ADD CONSTRAINT \"project_repo_installation_id_git_installation_id_fkey\" FOREIGN KEY (\"installation_id\") REFERENCES \"git_installation\"(\"id\") ON DELETE CASCADE;"
    ],
    "bps": true,
    "folderMillis": 1791448260000,
    "hash": "38151b4c03145f3c2eca1fed74ca1f9ad8eb9b470dd4ffe06a71aae978bcf44b",
    "name": "20261008083100_git_integrations"
  },
  {
    "sql": [
      "CREATE TYPE \"job_kind\" AS ENUM('deploy', 'preview-up', 'preview-rm');",
      "\nCREATE TYPE \"job_status\" AS ENUM('queued', 'claimed', 'running', 'done', 'failed', 'canceled');",
      "\nCREATE TYPE \"runner_kind\" AS ENUM('managed', 'self-hosted');",
      "\nCREATE TABLE \"job\" (\n\t\"id\" text PRIMARY KEY,\n\t\"project_id\" text NOT NULL,\n\t\"kind\" \"job_kind\" NOT NULL,\n\t\"status\" \"job_status\" DEFAULT 'queued'::\"job_status\" NOT NULL,\n\t\"pr\" integer DEFAULT 0 NOT NULL,\n\t\"sha\" text,\n\t\"branch\" text,\n\t\"labels\" text[] DEFAULT '{}'::text[] NOT NULL,\n\t\"dedupe_key\" text NOT NULL,\n\t\"event_at\" timestamp NOT NULL,\n\t\"runner_id\" text,\n\t\"lease_until\" timestamp,\n\t\"cancel_requested\" boolean DEFAULT false NOT NULL,\n\t\"claims\" integer DEFAULT 0 NOT NULL,\n\t\"deployment_id\" text,\n\t\"error\" text,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"claimed_at\" timestamp,\n\t\"started_at\" timestamp,\n\t\"finished_at\" timestamp,\n\t\"revision\" integer DEFAULT 1 NOT NULL,\n\t\"synced_revision\" integer DEFAULT 0 NOT NULL,\n\t\"changed_at\" timestamp DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"runner\" (\n\t\"id\" text PRIMARY KEY,\n\t\"organization_id\" text,\n\t\"kind\" \"runner_kind\" NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"labels\" text[] DEFAULT '{}'::text[] NOT NULL,\n\t\"public_key\" text NOT NULL,\n\t\"last_seen_at\" timestamp,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\tCONSTRAINT \"runner_managed_has_no_organization\" CHECK ((\"kind\" = 'managed') = (\"organization_id\" is null))\n);\n",
      "\nDROP TABLE \"git_delivery\";",
      "\nALTER TABLE \"project_repo\" ADD COLUMN \"production_branch\" text NOT NULL;",
      "\nALTER TABLE \"project_repo\" ADD COLUMN \"job_labels\" text[] DEFAULT '{}'::text[] NOT NULL;",
      "\nCREATE UNIQUE INDEX \"job_projectId_dedupeKey_uidx\" ON \"job\" (\"project_id\",\"dedupe_key\");",
      "\nCREATE UNIQUE INDEX \"job_projectId_pr_held_uidx\" ON \"job\" (\"project_id\",\"pr\") WHERE \"status\" in ('claimed', 'running');",
      "\nCREATE INDEX \"job_status_createdAt_idx\" ON \"job\" (\"status\",\"created_at\");",
      "\nCREATE INDEX \"job_projectId_pr_idx\" ON \"job\" (\"project_id\",\"pr\",\"created_at\");",
      "\nCREATE INDEX \"job_unsynced_idx\" ON \"job\" (\"changed_at\") WHERE \"revision\" <> \"synced_revision\";",
      "\nCREATE INDEX \"runner_organizationId_idx\" ON \"runner\" (\"organization_id\");",
      "\nALTER TABLE \"job\" ADD CONSTRAINT \"job_project_id_project_id_fkey\" FOREIGN KEY (\"project_id\") REFERENCES \"project\"(\"id\") ON DELETE CASCADE;",
      "\nALTER TABLE \"job\" ADD CONSTRAINT \"job_runner_id_runner_id_fkey\" FOREIGN KEY (\"runner_id\") REFERENCES \"runner\"(\"id\") ON DELETE SET NULL;",
      "\nALTER TABLE \"runner\" ADD CONSTRAINT \"runner_organization_id_organization_id_fkey\" FOREIGN KEY (\"organization_id\") REFERENCES \"organization\"(\"id\") ON DELETE CASCADE;"
    ],
    "bps": true,
    "folderMillis": 1791487018000,
    "hash": "d317fb9d1643f1209755e82bd50c0362a37411832b9a9bc31eebf769cbc37ec8",
    "name": "20261008191658_git_jobs"
  }
];
